In [1]:
import numpy as np

In [2]:
# 둘다 2x2행렬임!
A = np.array([[1,2],[3,4]])
B = np.array([[4,1],[5,2]])

In [3]:
A*B

array([[ 4,  2],
       [15,  8]])

In [5]:
# Transpose
a = np.array([[1,2],[3,4],[5,6]])

In [6]:
a_t = a.T

In [7]:
a_t

array([[1, 3, 5],
       [2, 4, 6]])

In [9]:
a_t_t = np.transpose(a_t)
a_t_t

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
# identity matrix
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
b = np.arange(9)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
b.resize(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
c = np.arange(9).reshape(3,3)
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])