In [2]:
import cv2
import numpy as np

In [3]:
cv2.__version__

'3.4.2'

In [4]:
# 이미지를 컬러로 로드하여 넘파이 배열 형태로 img에 대입합니다
img = cv2.imread('image.jpg', cv2.IMREAD_COLOR)

In [5]:
img

array([[[116, 137, 159],
        [119, 140, 162],
        [120, 141, 163],
        ...,
        [115, 116, 112],
        [113, 114, 110],
        [115, 113, 112]],

       [[114, 135, 157],
        [118, 139, 161],
        [120, 141, 163],
        ...,
        [115, 116, 112],
        [114, 115, 111],
        [114, 113, 109]],

       [[115, 136, 158],
        [119, 140, 162],
        [122, 143, 165],
        ...,
        [117, 118, 114],
        [116, 117, 113],
        [113, 114, 110]],

       ...,

       [[161, 151, 197],
        [162, 152, 198],
        [160, 150, 196],
        ...,
        [ 54,  93, 138],
        [ 54,  93, 138],
        [ 54,  93, 138]],

       [[160, 150, 196],
        [161, 151, 197],
        [161, 151, 197],
        ...,
        [ 56,  95, 140],
        [ 57,  96, 141],
        [ 57,  96, 141]],

       [[159, 149, 195],
        [161, 151, 197],
        [162, 152, 198],
        ...,
        [ 59,  98, 143],
        [ 59,  98, 143],
        [ 59,  98, 143]]

In [6]:
# 이미지가 저장된 넘파이 배열의 너비와 높이를 구합니다
height, width = img.shape[:2]
print(height,width)

2448 3264


In [7]:
# 이동 변환 행렬을 생성합니다. x방향으로 100픽셀, y방향으로 200픽셀 이동합니다
M = np.array([[1,0,100],[0,1,200],[0,0,1]],dtype = float)
M

array([[  1.,   0., 100.],
       [  0.,   1., 200.],
       [  0.,   0.,   1.]])

In [8]:
# 결과 이미지를 저장할 넘파이 배열을 입력 이미지와 같은 크기로 생성합니다
dst = np.zeros(img.shape, dtype = np.uint8)
dst

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [9]:
# 이미지의 전체 픽셀을 스캔합니다
for y in range(height-1):
    for x in range(width-1):
        
        # 현재 픽셀 p의 좌표에 이동 변환 행렬 M을 곱하여 이동시킨 좌표
        # p_를 구합니다
        p = np.array([x,y,1])
        p_ = np.dot(M,p)
        
        # 이동한 위치인 p_에서 좌표 x_,y_를 정수 형태로 가져옵니다
        x_,y_ = p_[:2]
        x_,y_ = int(x_),int(y_)
        
        # 입력 이미지 크기 내로 픽셀이 이동한 경우에만 결과 이미지를 저장할 넘파이 배열로 픽셀을 복사합니다
        if (0 <= x_ < width) and (0 <= y_ <height):
            dst[y_,x_] = img[y,x]

In [10]:
# cv2.imshow("img",img)

In [11]:
# 입력 이미지와 결과 이미지를 수평으로 연결하여 하나의 이미지로 만듭니다
result = cv2.hconcat([img,dst])

In [ ]:
# 타이틀 바에 result 문자열을 보여주는 윈도우에 이미지 result를 보여줍니다
cv2.imshow("result",result)

# 아무 키나 누르기 전까지 대기합니다.
cv2.waitKey(0)     # <- Key Uppercase